-- MySQL Script generated by MySQL Workbench
-- Wed May 21 22:30:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema task_collab_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_collab_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_collab_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `task_collab_db` ;

-- -----------------------------------------------------
-- Table `task_collab_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ultimo_acceso` DATETIME NULL DEFAULT NULL,
  `activo` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`tareas` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_vencimiento` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'en_progreso', 'completada', 'cancelada') NULL DEFAULT 'pendiente',
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tareas_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tareas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `task_collab_db`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`tipos_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`tipos_permiso` (
  `id_tipo_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_permiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`colaboradores_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`colaboradores_tarea` (
  `id_colaboradores_tarea` INT NOT NULL AUTO_INCREMENT,
  `id_tarea` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_tipo_permiso` INT NOT NULL,
  `fecha_asignacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_colaboradores_tarea`),
  INDEX `id_tarea` (`id_tarea` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_tipo_permiso` (`id_tipo_permiso` ASC) VISIBLE,
  CONSTRAINT `colaboradores_tarea_ibfk_1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `task_collab_db`.`tareas` (`id_tarea`)
    ON DELETE CASCADE,
  CONSTRAINT `colaboradores_tarea_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `task_collab_db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `colaboradores_tarea_ibfk_3`
    FOREIGN KEY (`id_tipo_permiso`)
    REFERENCES `task_collab_db`.`tipos_permiso` (`id_tipo_permiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_tarea` INT NOT NULL,
  `comentario` TEXT NOT NULL,
  `fecha_comentario` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comentario`),
  INDEX `id_tarea` (`id_tarea` ASC) VISIBLE,
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `task_collab_db`.`tareas` (`id_tarea`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`etiquetas` (
  `id_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `color` VARCHAR(7) NULL DEFAULT '#000000',
  PRIMARY KEY (`id_etiqueta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`historial_cambios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`historial_cambios` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_tarea` INT NOT NULL,
  `tipo_cambio` ENUM('creacion', 'modificacion', 'cambio_estado', 'cambio_prioridad', 'cambio_permiso') NOT NULL,
  `descripcion_cambio` TEXT NOT NULL,
  `fecha_cambio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `valor_anterior` VARCHAR(255) NULL DEFAULT NULL,
  `valor_nuevo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `id_tarea` (`id_tarea` ASC) VISIBLE,
  CONSTRAINT `historial_cambios_ibfk_1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `task_collab_db`.`tareas` (`id_tarea`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`prioridad` (
  `id_prioridad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
   `activo` BOOLEAN DEFAULT TRUE,
  `id_tares` INT NOT NULL,
  `tareas_id_tarea` INT NOT NULL,
  PRIMARY KEY (`id_prioridad`),
  INDEX `fk_prioridad_tareas1_idx` (`tareas_id_tarea` ASC) VISIBLE,
  CONSTRAINT `fk_prioridad_tareas1`
    FOREIGN KEY (`tareas_id_tarea`)
    REFERENCES `task_collab_db`.`tareas` (`id_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `task_collab_db`.`tareas_etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_collab_db`.`tareas_etiquetas` (
  `id_tarea_etiqueta` INT NOT NULL AUTO_INCREMENT,
  `id_tarea` INT NOT NULL,
  `id_etiqueta` INT NOT NULL,
  PRIMARY KEY (`id_tarea_etiqueta`),
  INDEX `id_tarea` (`id_tarea` ASC) VISIBLE,
  INDEX `id_etiqueta` (`id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `tareas_etiquetas_ibfk_1`
    FOREIGN KEY (`id_tarea`)
    REFERENCES `task_collab_db`.`tareas` (`id_tarea`)
    ON DELETE CASCADE,
  CONSTRAINT `tareas_etiquetas_ibfk_2`
    FOREIGN KEY (`id_etiqueta`)
    REFERENCES `task_collab_db`.`etiquetas` (`id_etiqueta`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
